# Generated by Django 3.2.13 on 2022-11-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='basic.jpg', upload_to='profile/%Y/%m/%d/'),
        ),
    ]
