# Generated by Django 3.2.13 on 2022-11-20 05:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_followings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followings',
        ),
        migrations.AddField(
            model_name='user',
            name='followings',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
